### ISSUE TITLE
Tutorial 1 files

### ISSUE THREAD

**Issue by Gomzi99** [PeterPopma/unityfc#1]
Please add files for tutorial 1 of the Soccer Game as there are some bugs that we are facing.

**Comment by PeterPopma** [comment]
You can find the code for part 1 at this commit:
https://github.com/PeterPopma/unityfc/commit/31a48b49030d704f333bf288c0872422dcc38603

Please report any bugs you encounter with the code.

**Comment by Gomzi99** [comment]
Hii Peter,
Hope you are doing perfectly fine.
I am a new comer to unity and saw your videos. Man you are GREAT! Firstly, I consider you my mentor and I Thank you on behalf of all the learners for providing such cool projects with such detailed explanations.

And secondly I did go through your video and the attested commit. I faced some bugs that I tried to resolve but couldn’t (at the point where the player kicks the ball, the animation changes and ball moves forward; timings around 41:00), in the soccer game first video. Hope you can look into it when you get time.
Please keep on creating such Projects and we will do our best to support you.

With Regards,
Tejasvi Birdh

**Comment by PeterPopma** [comment]
Hello Tejasvi,
Sorry but I am not sure where you are facing the bug.
Is it also in my code, or just on your side?
Is the kicking animation not playing? That could happen you have a few settings wrong.
If you want more recent code, I am now working on version 3 of the soccer game.
The repository is here: https://github.com/PeterPopma/KickIt
But be warned: it is not ready yet.

**Comment by Gomzi99** [comment]
Hello Peter,
Hope you are doing great!
Iam really looking forward to the version 3 of the game that you are making.

I am stuck at a point. The thing is I want the ball to follow a path when kicked which will be determined by a parabolic equation [kind of serialize the formula and value of the variables]. I looked into it in unity forums but didn’t find out anything to execute what I want.

Can you please guide me as to how I can go for it [asap] and if possible the version 3 that you are making, integrate this formula thingy with it so as the learners can be helped as there are many questions regarding this topic but no clarity.

Also can you please tell when will you be releasing the video for version 3. I am a 2nd year university student and have started learning unity with some of my friends. We all are thankful for your projects man.

Looking forward to your mail!
With regards,
Tejasvi Birdh
